server:
  port: 10020

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          order: 1
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
