server:
  port: 10012

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动
    url: jdbc:mysql://mistero.cn:13308/user_v2?zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: rollin
    password: 123456

  redis:
    host: 121.4.105.24
    port: 8000
    password: mistero

  cloud:
    nacos:
      config:
        server-addr: localhost:8848

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

# 定义 安全 相关
security:
  refers: http://127.0.0.1:10012/,http://127.0.0.1:10010/
  jwt:
    prefix: recordaccount_
    expiration: 86400000 # 过期时间默认一天 (单位：ms) -- 86400000 = 1天 -- 此处给出10天
    secretKey: recordaccount.jwt.secretkey
  login:
    accessTokenExpiration: 86400000 # AT 过期时间 - 1小时 = 3600000， 便于调试，此处暂时给出10天
  aes:
    secretKey: sP9dF2mR4zL6yH7w
  switchs:
    swaggerEnable: true # 定义Swagger开关，生产环境关闭
